### ISSUE TITLE
Create brand new login webpage

### ISSUE THREAD

**Issue by davidyanis** [Ranchino/Tech-Store#14]
Hello fellow colleagues. It's time for a new webpage. This webpage should have a logout button and a welcoming text, example _**Welcome, Username**._ Also a purchase history. You can choose to design this webpage however you like.

**_When you are signed in, this will appear._**
- [x] A logout button, when it's clicked it will take us to home page. 
- [x] Welcome _Username_ text. Print out with Javascript using a new function
- [x] Visible purchase history. Work with localStorage on this.

**Comment by Ranchino** [comment]
It´s finished now. 💯
