### ISSUE TITLE
Need new shopping cart site

### ISSUE THREAD

**Issue by davidyanis** [Ranchino/Tech-Store#3]
Can someone take this task? This is the site when shopping cart is clicked, it will take the customer to a "check out site".  It doesn't need functionality yet. It should fit for desktop, mobile and tablet. You can find design and layout inside our mockups folder. 

1. Create a file named shoppingcart.html.
2. Only make borders and buttons like on the image. Kindly use **flexbox** for this task.

@PCavar @Ranchino 

Many kisses /David

**Comment by PCavar** [comment]
i will fix it. 

kind regards P-dog

**Comment by PCavar** [comment]
i have done a push, please check it out, i have problems centering the content, and i also need to make a new button, will look att javascript.

**Comment by PCavar** [comment]
fixed som issues, still working on it.

**Comment by Ranchino** [comment]
Looks good, tell me if you need help.

**Comment by PCavar** [comment]
im done with this issue, im closing it.
