### ISSUE TITLE
Add a login function

### ISSUE THREAD

**Issue by Ranchino** [Ranchino/Tech-Store#5]
Create a form for login function.
Already registered user:
1. username
2. password
3. logg in button

If it is valid then link to a new page 
else alert a error sign.

Create a form for new user with input
1. username
2. password
3. mail
4. registration button.
Also when you have created a profile, a sign will show that everything is complete and now can log in. Then it will shift to login form.

**Comment by davidyanis** [comment]
good luck

**Comment by Ranchino** [comment]
finally it works and saving new users in a array in local storage.
