### ISSUE TITLE
Show amount of orders made

### ISSUE THREAD

**Issue by davidyanis** [Ranchino/Tech-Store#6]
Assignment: When "lägg till i kundvagnen" button is clicked, show amount of orders that user have done. This feature goes to left side of shopping cart icon. Save amount of orders with **localStorage** so every time user refreshes the amount of orders will still be there.

**Comment by Ranchino** [comment]
I see the shopping cart and it jumps when you add something (nicely), but it is undefined.

**Comment by davidyanis** [comment]
issue is solved now!
